name: agenda_app_with_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Cache
  hive_flutter: ^1.1.0
  hive: ^2.1.0

  path_provider: ^2.0.11

  # Service
  dio: ^4.0.6

  # Google
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  flutter_native_timezone: ^2.0.0
  uuid: ^3.0.6

  # Notification
  flutter_local_notifications: ^9.7.0

  # State Management
  provider: ^6.0.3

  # Widgetsw
  calendar_timeline: ^1.0.5
  syncfusion_flutter_charts: ^20.2.40
  omni_datetime_picker: ^0.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  hive_generator: ^1.1.3

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
